### PR TITLE
upgrade with backward compat to lsp4j 0.9.0

### PR DESCRIPTION
**Pull request by gayanper**
Upgrade to latest lsp4j 0.9.0

### CODE REVIEW

**Comment by NipunaRanasinghe** [comment]
@gayanper just to be sure, I think it would be okay to migrate the lsp4j version(without having a vote like last time ;)), as this time we ensure the backward compatibility for 0.8.x servers as well right?

**Comment by nixel2007** [comment]
Do we really need to preserve backward comapibility with lsp4j? it's just a wrapper over language server protocol, lsp4intellij doesn't call actual code of language servers, all of this is hidden behind jsop-rpc and lsp4j itself.

**Comment by nixel2007** [comment]
bsl ls migrated to lsp4j 0.9.0 but it works perfectly with lsp4intellij with lsp4j 0.8.0.

**Comment by gayanper** [comment]
I found few methods that doesn’t support when running with lsp4j 0.9.0 like the definitions endpoint which has new specific parameters. @Nipuna yes i have kept backward compatibility for methods that we have integrated in to IJ. But I directly changed the signatures of implementation and typeDefinition endpoints

**Comment by NipunaRanasinghe** [comment]
> Do we really need to preserve backward comapibility with lsp4j? it's just a wrapper over language server protocol, lsp4intellij doesn't call actual code of language servers, all of this is hidden behind jsop-rpc and lsp4j itself.

@nixel2007  0.9.0 release has introduced few method signature changes, which should break the compatibility between 0.8.x and .0.9.x servers/clients.
Its always not possible to do that with new lsp4j versions having backward incompatible changes. But what @gayanper has done is the right thing as we can make sure that aleast 0.8.x and 0.9.x servers will be compatible for now.

**Comment by NipunaRanasinghe** [comment]
> @nipuna yes i have kept backward compatibility for methods that we have integrated in to IJ. But I directly changed the signatures of implementation and typeDefinition endpoints

great! And I believe the reason why you directly changed the signatures for `implementation` and `typeDefinition` operations is we don't support them yet. So that would be fine I guess.

**Pull request merged**
