### PR TITLE
Deprecate getInitializationOptions() API and fix other deprecated usages

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
## Purpose
$subject. 

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by NipunaRanasinghe** [comment]
@payne911 Appreciate your thoughts on this

**Comment by payne911** [comment]
No problem. :)
I'm glad to see you're deprecating that other method. I had thought about it when making that other PR but then thought backward compatibility is generally appreciated by users.

**Review by aneeshafedo — APPROVED** [review]

**Comment by payne911** [comment]
> @payne911 Appreciate your review on this

Sorry, I just got back from vacation. It seems like this PR is merged now, but I still wanted to apologize. 👍

**Comment by mondhs** [comment]
I might miss something... 
I pulled master today, build lsp4intellij jar and added to my project.
I got yellow icon and my plugin was not working.
After analysis I found that with this pull request was changed LanguageServerWrapper#getInitParams(). 

It was removed:
```
initParams.setRootUri(FileUtils.pathToUri(projectRootPath));
```

but later in same method is used:
```
serverDefinition.getInitializationOptions(URI.create(initParams.getRootUri()))
```
Acodring javadoc [URI.create](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URI.html) this should cause always NPE . 

I removed the code my plugin started working. Should I create pull new pull request with removing the line?

**Pull request merged**
