### PR TITLE
prevent null pointer exception with languageServerWrapper when opening / closing files

### PR DESCRIPTION
**Pull request by johnamSyn**

### CODE REVIEW

**Comment by johnamSyn** [comment]
@NipunaRanasinghe if you have sometime to review my latest Pull requests it would be appreciated, thanks!

**Comment by NipunaRanasinghe** [comment]
> @NipunaRanasinghe if you have sometime to review my latest Pull requests it would be appreciated, thanks!

@johnamSyn Sure I'll make sure to get them merged. 

BTW could you please let us know if there any other fixes waiting from your side, so that we can wait a bit more before triggering a patch release with the current fixes?

**Review by NipunaRanasinghe — APPROVED** [review]

**Comment by johnamSyn** [comment]
@NipunaRanasinghe I will open one more ticket today with PR after that one is merged I think I will be done on my side

**Comment by NipunaRanasinghe** [comment]
> @NipunaRanasinghe I will open one more ticket today with PR after that one is merged I think I will be done on my side

Sounds great! :)

**Pull request merged**
