### PR TITLE
Support for LSP Spec 3 initialized request handling

### PR DESCRIPTION
**Pull request by gayanper**
With this change we will not allow any request to be send to server until the Initialized request is sent. This make this library to work well with a LS which follows the Spec 3. The name of the new status is not ideal, please feel free to suggest new name if required.

### CODE REVIEW

**Comment by rasika** [comment]
@gayanper This is great! Thanks for your contribution.  

I suppose state names need to be revamped. The state changes of `STOPPED -> STARTING -> STARTED_INIT_PENDING -> STARTED` seems bit odd to me. For the sake of readability, I would suggest is; `STOPPED -> STARTING -> STARTED -> INITIALIZED`

Therefore, shall we refactor `STARTED` into the `INITIALIZED`. Then add `STARTED` state as an intermediate state between `STARTING` and `INITIALIZED`. WDYT?

**Comment by NipunaRanasinghe** [comment]
Yeah I agree with @rasika's suggestion. On the other hand, do we really need 4 states to represent this life cycle?? I personally think that treating both of the `STARTING` and `STARTED_INIT_PENDING` states as `STARTING` state would make sense too. @gayanper WDYT??

**Comment by NipunaRanasinghe** [comment]
> Yeah I agree with @rasika's suggestion. On the other hand, do we really need 4 states to represent this life cycle?? I personally think that treating both of the `STARTING` and `STARTED_INIT_PENDING` states as `STARTING` state would make sense and will be less complicated. @gayanper WDYT??

**Comment by rasika** [comment]
@NipunaRanasinghe IMO still we need that separation of states. That would make it more cleaner.

**Comment by gayanper** [comment]
@NipunaRanasinghe i think we need a state to make sure that we only allow the initialized message to pass through. But STARTING can mean that the server is not yet started to receive requests from a consumers point of view. I know what you mean as well since how the code behaves we can assume that server is ready to receive requests even though the server is STARTING. But i do like @rasika suggestion. Shall we implement that if you don't see any drawbacks in this ?

**Comment by gayanper** [comment]
@rasika I have added the changes as we agreed on

**Comment by gayanper** [comment]
@NipunaRanasinghe can we get this merged ? Because some of my other changes are depended on this :(

**Comment by NipunaRanasinghe** [comment]
Sure will do :)

**Pull request merged**
