### PR TITLE
[Annotation][QuickFix] the register action logic is after mouse cursor moving on diagnostic annotation, and modify it to createAnnotation logic

### PR DESCRIPTION
**Pull request by MagicRUBICK**
image

### CODE REVIEW

**Comment by NipunaRanasinghe** [comment]
@MagicRUBICK This is actually the previous implementation we had and let me explain why we had to move to a more complex diagnostics + code actions implementation.

Basically there are two scenarios which this IntelliJ language client should be able to handle
1. Diagnostics based quick fixes (which you've adressed)
2. Line based quick fixes (which you've missed)

Language server protocol allows providing code actions for a defined range(usually line-based) even without having any diagnostics present on a particular line. Therefore we need to request code actions in each time where the cursor position is moved to a new line. (this is being done by vscode language client as well). On the other hand there might be a considerable performance cost if we always send code actions request on each diagnostic notification coming from the lang server side. So the current implementation is more likely a lazy loading approach. Hope you understand the complications and reasons for the current approach. :)

**Comment by MagicRUBICK** [comment]
Got it, thx. 
Do you know how is the implement in VSCode.

**Comment by NipunaRanasinghe** [comment]
@MagicRUBICK Sorry I haven't had a chance to work on vscode developments so far :/ AFAIR vscode language client is well documented so you might be able to have a clue there :)

**Comment by NipunaRanasinghe** [comment]
Closing the PR as per the above discussion.

**Pull request closed without merging**
