### PR TITLE
Fix deprecations

### LINKED ISSUE #190: [plugin compat] usages of scheduled for removal API
4 usages of scheduled for removal API

StatusBarWidget.PlatformType (2) (scheduled for removal in 2020.2)
  Deprecated enum StatusBarWidget.PlatformType is referenced in 
    LSPServerStatusWidget.getPresentation(...). This enum will be removed in 2020.2
  Deprecated enum StatusBarWidget.PlatformType is referenced in 
    LSPServerStatusWidget.getPresentation(...). This enum will be removed in 2020.2

Scheduled for removal methods usages (2)
  StatusBar.addWidget(StatusBarWidget, String) (1) (scheduled for removal in a future release)
  StatusBarWidget.getPresentation(...) (1) (scheduled for removal in 2020.2)

### PR DESCRIPTION
**Pull request by Trias**
this resolves #190, #189, #184

and prepares for #192, #175

NOTE: This also raises the minimum IJ version to 2021.1 and Java version to 11!

I've also adjusted parts of the documentation, which i hope is clearer now.

Note that the plugin.xml-setup is now more complex, as all the listerners get to be defined in the xml instead of IntellijLanguageClient. I've added an example to cover that. Also i deprecated the Plugin-Components approach in the documentation  (which should still work however)

Note that i did not test all changes, as my Language server does not cover all use cases. I believe however that these changes are minor and hopefully work.

To cover #175 & #192 we need to use Services, which should be easy to do however, they just need to be registered in plugin.xml. We also probably should not store stuff in static variables, in order to be compatible/avoid memleaks, so there is some work to be done.

### CODE REVIEW

**Comment by Trias** [comment]
Sample output of "runPluginVerifier":

(we cannot fix these deprecations as they are either required by the interfaces or to support components based approach)
```
Deprecated API usages (6): 
    #Deprecated method com.intellij.openapi.components.BaseComponent.initComponent() is overridden
        Deprecated method com.intellij.openapi.components.BaseComponent.initComponent() : void is overridden in class org.wso2.lsp4intellij.IntellijLanguageClient
    #Deprecated interface com.intellij.openapi.components.ApplicationComponent reference
        Deprecated interface com.intellij.openapi.components.ApplicationComponent is referenced in org.wso2.lsp4intellij.IntellijLanguageClient
    #Deprecated method com.intellij.psi.PsiElement.checkAdd(PsiElement) is overridden
        Deprecated method com.intellij.psi.PsiElement.checkAdd(com.intellij.psi.PsiElement arg0) : void is overridden in class org.wso2.lsp4intellij.contributors.psi.LSPPsiElement
    #Deprecated method com.intellij.openapi.vfs.VirtualFileManager.addVirtualFileListener(VirtualFileListener) invocation
        Deprecated method com.intellij.openapi.vfs.VirtualFileManager.addVirtualFileListener(com.intellij.openapi.vfs.VirtualFileListener arg0) : void is invoked in org.wso2.lsp4intellij.IntellijLanguageClient.initComponent() : void
    #Deprecated method com.intellij.openapi.components.BaseComponent.disposeComponent() is overridden
        Deprecated method com.intellij.openapi.components.BaseComponent.disposeComponent() : void is overridden in class org.wso2.lsp4intellij.IntellijLanguageClient
    #Deprecated method com.intellij.psi.PsiElement.checkDelete() is overridden
        Deprecated method com.intellij.psi.PsiElement.checkDelete() : void is overridden in class org.wso2.lsp4intellij.contributors.psi.LSPPsiElement
    Plugin can be loaded/unloaded without IDE restart
```

**Comment by nixel2007** [comment]
> Note that i did not test all changes, as my Language server does not cover all use cases.

Hello! Ping me, if you need help with testing of code diagnostics, workspace symbols, hover and find references.

**Comment by Trias** [comment]
> > Note that i did not test all changes, as my Language server does not cover all use cases.
> 
> Hello! Ping me, if you need help with testing of code diagnostics, workspace symbols, hover and find references.

Thank you! You may checkout this branch and test it with your Language server. the relevant commit is https://github.com/ballerina-platform/lsp4intellij/pull/251/commits/eca4495bed5d685ffcedfbcdbd88d3e8fa51a715

it concerns references, notifications & rename

**Comment by Trias** [comment]
I'm not really shure how i should fix the spotbugs warnings. In my opinion they are false positives. or am i missing something? 
image

**Comment by Trias** [comment]
hm.. now only java 8 fails, but it's no longer compatible and i removed it from the build task... maybe s/o with write access can fix this?

**Comment by NipunaRanasinghe** [comment]
@Trias Losing support for java8 seems okay, but changing the minimum compatible IDEA version to 2021.1 is the concern. Even if the plugin verifier fails for older IntelliJ platform version, I guess that would be okay if the client *can run smoothly* on older versions.

**Review by NipunaRanasinghe — APPROVED** [review]

**Pull request merged**
