### PR TITLE
Add LabelProvider for LPS elements such as symbols.

### PR DESCRIPTION
**Pull request by gayanper**
The default label provider is used by when no custom label
provider is provided.

### CODE REVIEW

**Comment by gayanper** [comment]
When merging this probably you will get conflicts, That is because this PR depends on other PRs changes i have made. Therefore keep this PR to be merge last so i can resolve the conflicts to make it mergable.

**Comment by NipunaRanasinghe** [comment]
As you've mentioned, shall we resolve the conflicts after merging the rest of the PRs (and it would be great if you can squash the commits as well) and review afterwards? :)

**Comment by gayanper** [comment]
Will do that 👍

**Comment by NipunaRanasinghe** [comment]
@gayanper I guess now you can work on this now as I've merged the other PRs :)

**Comment by gayanper** [comment]
@NipunaRanasinghe this now ready to be merged, after this merged to master i will work on the next PR.

**Comment by NipunaRanasinghe** [comment]
I would be great to have some squashing as well :)

**Comment by gayanper** [comment]
Sure i will check that this weekend.

**Comment by gayanper** [comment]
@NipunaRanasinghe you can check this now, Let me know if you need more changes.

**Comment by NipunaRanasinghe** [comment]
@gayanper Really appreciate your effort on improving the user API :) I'll merge this so that you can resolve conflicts and proceed with the rest of the PRs.

**Pull request merged**
