### PR TITLE
Language client context and custom language client implementation.

### PR DESCRIPTION
**Pull request by gayanper**
To efficiently find Editor the language client context is introduce for
example which hold EditorEventManager for document URIs. With that you
can provide your own language client implementation.

Signed-off-by: gayanper <gayanper@gmail.com>

### CODE REVIEW

**Comment by gayanper** [comment]
@rasika and @NipunaRanasinghe what do you think about these changes ?

**Comment by NipunaRanasinghe** [comment]
@gayanper Small question, with your changes do we still need to allow DefaultRequestManager to be extended via ExtensionManager interface? I think we don't need to right?? :)

**Comment by gayanper** [comment]
@NipunaRanasinghe sorry i didn't got your question. The `DefaultRequestManager` doesn't extend the `ExtentionManager` right ?

**Comment by NipunaRanasinghe** [comment]
> @NipunaRanasinghe sorry i didn't got your question. The `DefaultRequestManager` doesn't extend the `ExtentionManager` right ?

I asked whether we want to keep `getExtendedRequestManagerFor()` in `LSPExtensionManager` since we have the access to the languageclient implementation now

**Comment by gayanper** [comment]
@NipunaRanasinghe well what if a consumer want the request manager but has no need for extending the language client. IMHO it seems bit odd for some one to implement a totally different component to access the component they want, i mean after that the consumer might also need to store the request manager in a singleton context as well. Let me know what you think :)

**Comment by NipunaRanasinghe** [comment]
@gayanper Yeah thats a valid concern, I'm just thinking of ways to improve the extend-ability of the library :) thanks!

**Pull request merged**
