### PR TITLE
Add LSPSymbolContributor for showing symbols from LSP client

### PR DESCRIPTION
**Pull request by gayanper**
## Purpose
Add symbol support with minimum set of icon types that are commonly used.

### CODE REVIEW

**Comment by NipunaRanasinghe** [comment]
Seems there is a merge conflict after merging the Timeouts API :/ Shall we fix?

**Comment by gayanper** [comment]
Will update the PR tonight. @NipunaRanasinghe are you ok with the approach ?

**Comment by NipunaRanasinghe** [comment]
@gayanper I'll try building your branch and verify after testing with ballerina language server as well :)

**Comment by gayanper** [comment]
@NipunaRanasinghe  conflicts resolved. i rebase the master branch and forced push the changes to make the commits clean.

**Comment by NipunaRanasinghe** [comment]
@gayanper Unfortunately we still have conflicts after merging the file pattern related PR. :(

**Comment by gayanper** [comment]
I'll have a look at it tonight

**Comment by NipunaRanasinghe** [comment]
@gayanper I tested your branch locally with the ballerina language server and it worked perfectly :)

**Pull request merged**
