### PR TITLE
Add proper shutdown support when closing IDE window

### PR DESCRIPTION
**Pull request by gayanper**
Add support for shutting down language server when IDE window is closed and IDEA jvm is forcefully stopped.

### CODE REVIEW

**Comment by gayanper** [comment]
@Nipuna hold this off i need to do some more testing. I think i should only stop if its only running. Now we try to stop the same server twice 😔. My bad i didn't check the stop method frankly before pushing this change. Late night mistakes 😒

**Comment by NipunaRanasinghe** [comment]
Hey no worries @gayanper! Take your time and let me know when your PR is ready :) may be you can do some more debugging to see whats really going wrong with the shutdown request

**Comment by gayanper** [comment]
Cleanup the code and add more fixes to stop exception when a server listener is used.

**Comment by gayanper** [comment]
@NipunaRanasinghe you can review now

**Comment by gayanper** [comment]
@NipunaRanasinghe any update on this PR ?

**Comment by NipunaRanasinghe** [comment]
@gayanper Thanks for the improvements :)

**Pull request merged**
